POST http://localhost:3000/api/days
content-type: application/json

{
    "date": {
        "day": 18,
        "month": 09,
        "year": 2022
    },
    "battles": [
        {
            "points": 4
        }
    ]
}

###

PATCH http://localhost:3000/api/days
content-type: application/json

{
    "date": {
        "day": 15,
        "month": 09,
        "year": 2022
    },
    "battles": [
        {
            "points": 4
        }
    ]
}
###

GET http://localhost:3000/api/days
content-type: application/json